/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/room": {
    get: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          agenda_id?: parameters["rowFilter.room.agenda_id"];
          /** Notion ID. */
          current_slide_id?: parameters["rowFilter.room.current_slide_id"];
          timer_state?: parameters["rowFilter.room.timer_state"];
          timer_start_time?: parameters["rowFilter.room.timer_start_time"];
          timer_end_time?: parameters["rowFilter.room.timer_end_time"];
          id?: parameters["rowFilter.room.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["room"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** room */
          room?: definitions["room"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          agenda_id?: parameters["rowFilter.room.agenda_id"];
          /** Notion ID. */
          current_slide_id?: parameters["rowFilter.room.current_slide_id"];
          timer_state?: parameters["rowFilter.room.timer_state"];
          timer_start_time?: parameters["rowFilter.room.timer_start_time"];
          timer_end_time?: parameters["rowFilter.room.timer_end_time"];
          id?: parameters["rowFilter.room.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          agenda_id?: parameters["rowFilter.room.agenda_id"];
          /** Notion ID. */
          current_slide_id?: parameters["rowFilter.room.current_slide_id"];
          timer_state?: parameters["rowFilter.room.timer_state"];
          timer_start_time?: parameters["rowFilter.room.timer_start_time"];
          timer_end_time?: parameters["rowFilter.room.timer_end_time"];
          id?: parameters["rowFilter.room.id"];
        };
        body: {
          /** room */
          room?: definitions["room"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  room: {
    /** Human readable name. */
    name?: string;
    /** URL path to access this room. */
    slug?: string;
    /** Notion property. */
    agenda_id?: string;
    /** Notion ID. */
    current_slide_id?: string;
    timer_state?: string;
    timer_start_time?: string;
    timer_end_time?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** room */
  "body.room": definitions["room"];
  /** Human readable name. */
  "rowFilter.room.name": string;
  /** URL path to access this room. */
  "rowFilter.room.slug": string;
  /** Notion property. */
  "rowFilter.room.agenda_id": string;
  /** Notion ID. */
  "rowFilter.room.current_slide_id": string;
  "rowFilter.room.timer_state": string;
  "rowFilter.room.timer_start_time": string;
  "rowFilter.room.timer_end_time": string;
  "rowFilter.room.id": string;
}

export interface operations {}

export interface external {}
