/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          insertedAt?: parameters["rowFilter.profile.insertedAt"];
          updatedAt?: parameters["rowFilter.profile.updatedAt"];
          canLeadSessions?: parameters["rowFilter.profile.canLeadSessions"];
          firstName?: parameters["rowFilter.profile.firstName"];
          lastName?: parameters["rowFilter.profile.lastName"];
          userId?: parameters["rowFilter.profile.userId"];
          canManageShifts?: parameters["rowFilter.profile.canManageShifts"];
          email?: parameters["rowFilter.profile.email"];
          id?: parameters["rowFilter.profile.id"];
          hubspotContactId?: parameters["rowFilter.profile.hubspotContactId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          insertedAt?: parameters["rowFilter.profile.insertedAt"];
          updatedAt?: parameters["rowFilter.profile.updatedAt"];
          canLeadSessions?: parameters["rowFilter.profile.canLeadSessions"];
          firstName?: parameters["rowFilter.profile.firstName"];
          lastName?: parameters["rowFilter.profile.lastName"];
          userId?: parameters["rowFilter.profile.userId"];
          canManageShifts?: parameters["rowFilter.profile.canManageShifts"];
          email?: parameters["rowFilter.profile.email"];
          id?: parameters["rowFilter.profile.id"];
          hubspotContactId?: parameters["rowFilter.profile.hubspotContactId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          insertedAt?: parameters["rowFilter.profile.insertedAt"];
          updatedAt?: parameters["rowFilter.profile.updatedAt"];
          canLeadSessions?: parameters["rowFilter.profile.canLeadSessions"];
          firstName?: parameters["rowFilter.profile.firstName"];
          lastName?: parameters["rowFilter.profile.lastName"];
          userId?: parameters["rowFilter.profile.userId"];
          canManageShifts?: parameters["rowFilter.profile.canManageShifts"];
          email?: parameters["rowFilter.profile.email"];
          id?: parameters["rowFilter.profile.id"];
          hubspotContactId?: parameters["rowFilter.profile.hubspotContactId"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/room": {
    get: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          slideshowName?: parameters["rowFilter.room.slideshowName"];
          /** Notion ID. */
          currentSlideIndex?: parameters["rowFilter.room.currentSlideIndex"];
          timerState?: parameters["rowFilter.room.timerState"];
          timerStartTime?: parameters["rowFilter.room.timerStartTime"];
          timerDuration?: parameters["rowFilter.room.timerDuration"];
          wherebyMeetingId?: parameters["rowFilter.room.wherebyMeetingId"];
          wherebyStartDate?: parameters["rowFilter.room.wherebyStartDate"];
          wherebyEndDate?: parameters["rowFilter.room.wherebyEndDate"];
          wherebyRoomUrl?: parameters["rowFilter.room.wherebyRoomUrl"];
          wherebyHostRoomUrl?: parameters["rowFilter.room.wherebyHostRoomUrl"];
          id?: parameters["rowFilter.room.id"];
          hubspotLeaderListId?: parameters["rowFilter.room.hubspotLeaderListId"];
          updatedAt?: parameters["rowFilter.room.updatedAt"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["room"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** room */
          room?: definitions["room"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          slideshowName?: parameters["rowFilter.room.slideshowName"];
          /** Notion ID. */
          currentSlideIndex?: parameters["rowFilter.room.currentSlideIndex"];
          timerState?: parameters["rowFilter.room.timerState"];
          timerStartTime?: parameters["rowFilter.room.timerStartTime"];
          timerDuration?: parameters["rowFilter.room.timerDuration"];
          wherebyMeetingId?: parameters["rowFilter.room.wherebyMeetingId"];
          wherebyStartDate?: parameters["rowFilter.room.wherebyStartDate"];
          wherebyEndDate?: parameters["rowFilter.room.wherebyEndDate"];
          wherebyRoomUrl?: parameters["rowFilter.room.wherebyRoomUrl"];
          wherebyHostRoomUrl?: parameters["rowFilter.room.wherebyHostRoomUrl"];
          id?: parameters["rowFilter.room.id"];
          hubspotLeaderListId?: parameters["rowFilter.room.hubspotLeaderListId"];
          updatedAt?: parameters["rowFilter.room.updatedAt"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          /** Human readable name. */
          name?: parameters["rowFilter.room.name"];
          /** URL path to access this room. */
          slug?: parameters["rowFilter.room.slug"];
          /** Notion property. */
          slideshowName?: parameters["rowFilter.room.slideshowName"];
          /** Notion ID. */
          currentSlideIndex?: parameters["rowFilter.room.currentSlideIndex"];
          timerState?: parameters["rowFilter.room.timerState"];
          timerStartTime?: parameters["rowFilter.room.timerStartTime"];
          timerDuration?: parameters["rowFilter.room.timerDuration"];
          wherebyMeetingId?: parameters["rowFilter.room.wherebyMeetingId"];
          wherebyStartDate?: parameters["rowFilter.room.wherebyStartDate"];
          wherebyEndDate?: parameters["rowFilter.room.wherebyEndDate"];
          wherebyRoomUrl?: parameters["rowFilter.room.wherebyRoomUrl"];
          wherebyHostRoomUrl?: parameters["rowFilter.room.wherebyHostRoomUrl"];
          id?: parameters["rowFilter.room.id"];
          hubspotLeaderListId?: parameters["rowFilter.room.hubspotLeaderListId"];
          updatedAt?: parameters["rowFilter.room.updatedAt"];
        };
        body: {
          /** room */
          room?: definitions["room"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/roompermission": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roompermission.id"];
          /** member | leader | manager */
          type?: parameters["rowFilter.roompermission.type"];
          updatedAt?: parameters["rowFilter.roompermission.updatedAt"];
          profileId?: parameters["rowFilter.roompermission.profileId"];
          roomId?: parameters["rowFilter.roompermission.roomId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["roompermission"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** roompermission */
          roompermission?: definitions["roompermission"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roompermission.id"];
          /** member | leader | manager */
          type?: parameters["rowFilter.roompermission.type"];
          updatedAt?: parameters["rowFilter.roompermission.updatedAt"];
          profileId?: parameters["rowFilter.roompermission.profileId"];
          roomId?: parameters["rowFilter.roompermission.roomId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roompermission.id"];
          /** member | leader | manager */
          type?: parameters["rowFilter.roompermission.type"];
          updatedAt?: parameters["rowFilter.roompermission.updatedAt"];
          profileId?: parameters["rowFilter.roompermission.profileId"];
          roomId?: parameters["rowFilter.roompermission.roomId"];
        };
        body: {
          /** roompermission */
          roompermission?: definitions["roompermission"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/shiftallocation": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftallocation.id"];
          shiftPatternId?: parameters["rowFilter.shiftallocation.shiftPatternId"];
          profileId?: parameters["rowFilter.shiftallocation.profileId"];
          updatedAt?: parameters["rowFilter.shiftallocation.updatedAt"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["shiftallocation"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shiftallocation */
          shiftallocation?: definitions["shiftallocation"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftallocation.id"];
          shiftPatternId?: parameters["rowFilter.shiftallocation.shiftPatternId"];
          profileId?: parameters["rowFilter.shiftallocation.profileId"];
          updatedAt?: parameters["rowFilter.shiftallocation.updatedAt"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftallocation.id"];
          shiftPatternId?: parameters["rowFilter.shiftallocation.shiftPatternId"];
          profileId?: parameters["rowFilter.shiftallocation.profileId"];
          updatedAt?: parameters["rowFilter.shiftallocation.updatedAt"];
        };
        body: {
          /** shiftallocation */
          shiftallocation?: definitions["shiftallocation"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/shiftexception": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftexception.id"];
          shiftPatternId?: parameters["rowFilter.shiftexception.shiftPatternId"];
          date?: parameters["rowFilter.shiftexception.date"];
          profileId?: parameters["rowFilter.shiftexception.profileId"];
          /** drop_out or drop_in */
          type?: parameters["rowFilter.shiftexception.type"];
          lastUpdated?: parameters["rowFilter.shiftexception.lastUpdated"];
          shiftAllocationId?: parameters["rowFilter.shiftexception.shiftAllocationId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["shiftexception"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shiftexception */
          shiftexception?: definitions["shiftexception"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftexception.id"];
          shiftPatternId?: parameters["rowFilter.shiftexception.shiftPatternId"];
          date?: parameters["rowFilter.shiftexception.date"];
          profileId?: parameters["rowFilter.shiftexception.profileId"];
          /** drop_out or drop_in */
          type?: parameters["rowFilter.shiftexception.type"];
          lastUpdated?: parameters["rowFilter.shiftexception.lastUpdated"];
          shiftAllocationId?: parameters["rowFilter.shiftexception.shiftAllocationId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.shiftexception.id"];
          shiftPatternId?: parameters["rowFilter.shiftexception.shiftPatternId"];
          date?: parameters["rowFilter.shiftexception.date"];
          profileId?: parameters["rowFilter.shiftexception.profileId"];
          /** drop_out or drop_in */
          type?: parameters["rowFilter.shiftexception.type"];
          lastUpdated?: parameters["rowFilter.shiftexception.lastUpdated"];
          shiftAllocationId?: parameters["rowFilter.shiftexception.shiftAllocationId"];
        };
        body: {
          /** shiftexception */
          shiftexception?: definitions["shiftexception"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/shiftpattern": {
    get: {
      parameters: {
        query: {
          name?: parameters["rowFilter.shiftpattern.name"];
          required_people?: parameters["rowFilter.shiftpattern.required_people"];
          id?: parameters["rowFilter.shiftpattern.id"];
          roomId?: parameters["rowFilter.shiftpattern.roomId"];
          updatedAt?: parameters["rowFilter.shiftpattern.updatedAt"];
          cron?: parameters["rowFilter.shiftpattern.cron"];
          allowOneOffAllocations?: parameters["rowFilter.shiftpattern.allowOneOffAllocations"];
          cronTimezone?: parameters["rowFilter.shiftpattern.cronTimezone"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["shiftpattern"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shiftpattern */
          shiftpattern?: definitions["shiftpattern"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          name?: parameters["rowFilter.shiftpattern.name"];
          required_people?: parameters["rowFilter.shiftpattern.required_people"];
          id?: parameters["rowFilter.shiftpattern.id"];
          roomId?: parameters["rowFilter.shiftpattern.roomId"];
          updatedAt?: parameters["rowFilter.shiftpattern.updatedAt"];
          cron?: parameters["rowFilter.shiftpattern.cron"];
          allowOneOffAllocations?: parameters["rowFilter.shiftpattern.allowOneOffAllocations"];
          cronTimezone?: parameters["rowFilter.shiftpattern.cronTimezone"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          name?: parameters["rowFilter.shiftpattern.name"];
          required_people?: parameters["rowFilter.shiftpattern.required_people"];
          id?: parameters["rowFilter.shiftpattern.id"];
          roomId?: parameters["rowFilter.shiftpattern.roomId"];
          updatedAt?: parameters["rowFilter.shiftpattern.updatedAt"];
          cron?: parameters["rowFilter.shiftpattern.cron"];
          allowOneOffAllocations?: parameters["rowFilter.shiftpattern.allowOneOffAllocations"];
          cronTimezone?: parameters["rowFilter.shiftpattern.cronTimezone"];
        };
        body: {
          /** shiftpattern */
          shiftpattern?: definitions["shiftpattern"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/http_put": {
    post: {
      parameters: {
        body: {
          args: {
            content: string;
            content_type: string;
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_header": {
    post: {
      parameters: {
        body: {
          args: {
            field: string;
            value: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_patch": {
    post: {
      parameters: {
        body: {
          args: {
            content: string;
            content_type: string;
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_set_curlopt": {
    post: {
      parameters: {
        body: {
          args: {
            curlopt: string;
            value: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_get": {
    post: {
      parameters: {
        body: {
          args: {
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http": {
    post: {
      parameters: {
        body: {
          args: {
            request: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_delete": {
    post: {
      parameters: {
        body: {
          args: {
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_head": {
    post: {
      parameters: {
        body: {
          args: {
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_reset_curlopt": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/http_post": {
    post: {
      parameters: {
        body: {
          args: {
            content: string;
            content_type: string;
            uri: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/urlencode": {
    post: {
      parameters: {
        body: {
          args: {
            string: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  profile: {
    insertedAt: string;
    updatedAt: string;
    canLeadSessions: boolean;
    firstName?: string;
    lastName?: string;
    userId?: string;
    canManageShifts: boolean;
    email: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    hubspotContactId?: string;
  };
  room: {
    /** Human readable name. */
    name: string;
    /** URL path to access this room. */
    slug: string;
    /** Notion property. */
    slideshowName: string;
    /** Notion ID. */
    currentSlideIndex: number;
    timerState?: string;
    timerStartTime: string;
    timerDuration: number;
    wherebyMeetingId?: string;
    wherebyStartDate?: string;
    wherebyEndDate?: string;
    wherebyRoomUrl?: string;
    wherebyHostRoomUrl?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    hubspotLeaderListId?: string;
    updatedAt: string;
  };
  roompermission: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** member | leader | manager */
    type: string;
    updatedAt: string;
    /**
     * Note:
     * This is a Foreign Key to `profile.id`.<fk table='profile' column='id'/>
     */
    profileId: string;
    /**
     * Note:
     * This is a Foreign Key to `room.id`.<fk table='room' column='id'/>
     */
    roomId: string;
  };
  shiftallocation: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `shiftpattern.id`.<fk table='shiftpattern' column='id'/>
     */
    shiftPatternId: string;
    /**
     * Note:
     * This is a Foreign Key to `profile.id`.<fk table='profile' column='id'/>
     */
    profileId: string;
    updatedAt: string;
  };
  shiftexception: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `shiftpattern.id`.<fk table='shiftpattern' column='id'/>
     */
    shiftPatternId: string;
    date: string;
    /**
     * Note:
     * This is a Foreign Key to `profile.id`.<fk table='profile' column='id'/>
     */
    profileId: string;
    /** drop_out or drop_in */
    type: string;
    lastUpdated: string;
    /**
     * Note:
     * This is a Foreign Key to `shiftallocation.id`.<fk table='shiftallocation' column='id'/>
     */
    shiftAllocationId?: string;
  };
  shiftpattern: {
    name: string;
    required_people: number;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `room.id`.<fk table='room' column='id'/>
     */
    roomId: string;
    updatedAt: string;
    cron: string;
    allowOneOffAllocations: boolean;
    cronTimezone: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** profile */
  "body.profile": definitions["profile"];
  "rowFilter.profile.insertedAt": string;
  "rowFilter.profile.updatedAt": string;
  "rowFilter.profile.canLeadSessions": string;
  "rowFilter.profile.firstName": string;
  "rowFilter.profile.lastName": string;
  "rowFilter.profile.userId": string;
  "rowFilter.profile.canManageShifts": string;
  "rowFilter.profile.email": string;
  "rowFilter.profile.id": string;
  "rowFilter.profile.hubspotContactId": string;
  /** room */
  "body.room": definitions["room"];
  /** Human readable name. */
  "rowFilter.room.name": string;
  /** URL path to access this room. */
  "rowFilter.room.slug": string;
  /** Notion property. */
  "rowFilter.room.slideshowName": string;
  /** Notion ID. */
  "rowFilter.room.currentSlideIndex": string;
  "rowFilter.room.timerState": string;
  "rowFilter.room.timerStartTime": string;
  "rowFilter.room.timerDuration": string;
  "rowFilter.room.wherebyMeetingId": string;
  "rowFilter.room.wherebyStartDate": string;
  "rowFilter.room.wherebyEndDate": string;
  "rowFilter.room.wherebyRoomUrl": string;
  "rowFilter.room.wherebyHostRoomUrl": string;
  "rowFilter.room.id": string;
  "rowFilter.room.hubspotLeaderListId": string;
  "rowFilter.room.updatedAt": string;
  /** roompermission */
  "body.roompermission": definitions["roompermission"];
  "rowFilter.roompermission.id": string;
  /** member | leader | manager */
  "rowFilter.roompermission.type": string;
  "rowFilter.roompermission.updatedAt": string;
  "rowFilter.roompermission.profileId": string;
  "rowFilter.roompermission.roomId": string;
  /** shiftallocation */
  "body.shiftallocation": definitions["shiftallocation"];
  "rowFilter.shiftallocation.id": string;
  "rowFilter.shiftallocation.shiftPatternId": string;
  "rowFilter.shiftallocation.profileId": string;
  "rowFilter.shiftallocation.updatedAt": string;
  /** shiftexception */
  "body.shiftexception": definitions["shiftexception"];
  "rowFilter.shiftexception.id": string;
  "rowFilter.shiftexception.shiftPatternId": string;
  "rowFilter.shiftexception.date": string;
  "rowFilter.shiftexception.profileId": string;
  /** drop_out or drop_in */
  "rowFilter.shiftexception.type": string;
  "rowFilter.shiftexception.lastUpdated": string;
  "rowFilter.shiftexception.shiftAllocationId": string;
  /** shiftpattern */
  "body.shiftpattern": definitions["shiftpattern"];
  "rowFilter.shiftpattern.name": string;
  "rowFilter.shiftpattern.required_people": string;
  "rowFilter.shiftpattern.id": string;
  "rowFilter.shiftpattern.roomId": string;
  "rowFilter.shiftpattern.updatedAt": string;
  "rowFilter.shiftpattern.cron": string;
  "rowFilter.shiftpattern.allowOneOffAllocations": string;
  "rowFilter.shiftpattern.cronTimezone": string;
}

export interface operations {}

export interface external {}
